#!/usr/bin/python3



with open('malicious1', 'r') as BL1:
    with open('Malicious', 'w+') as BL:
        for line in BL1:
            BL.write('{} {}\n'.format(line.strip(), 'malicious'))
            
        
